ALTER TABLE games
    DROP CONSTRAINT games_current_player_id_fkey;

ALTER TABLE games
    DROP CONSTRAINT games_player_o_id_fkey;

ALTER TABLE games
    DROP CONSTRAINT games_player_x_id_fkey;

ALTER TABLE games
    DROP CONSTRAINT games_winner_id_fkey;

ALTER TABLE invitations
    DROP CONSTRAINT invitations_receiver_id_fkey;

ALTER TABLE invitations
    DROP CONSTRAINT invitations_sender_id_fkey;

ALTER TABLE moves
    DROP CONSTRAINT moves_game_id_fkey;

ALTER TABLE moves
    DROP CONSTRAINT moves_user_id_fkey;

CREATE TABLE base_entity
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    dtype             VARCHAR(31),
    updated_at        TIMESTAMP WITHOUT TIME ZONE,
    created_at        TIMESTAMP WITHOUT TIME ZONE,
    status            SMALLINT,
    creator_id        BIGINT,
    inline_message_id INTEGER,
    player_x          BIGINT,
    player_o          BIGINT,
    game_board        BYTEA,
    fullname          VARCHAR(255),
    username          VARCHAR(255),
    language          SMALLINT,
    language_code     VARCHAR(255),
    game_id           BIGINT,
    message_id        INTEGER,
    player_symbol     VARCHAR(255),
    bot_symbol        VARCHAR(255),
    difficulty_level  SMALLINT,
    CONSTRAINT pk_baseentity PRIMARY KEY (id)
);

DROP TABLE games CASCADE;

DROP TABLE invitations CASCADE;

DROP TABLE moves CASCADE;

DROP TABLE multiplayer_games CASCADE;

DROP TABLE product CASCADE;

DROP TABLE users CASCADE;

DROP TABLE web_users CASCADE;